# This workflow will do a clean installation of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu]
        node-version: [14.x, 16.x, 18.x]
        hapi-version: [20, 21]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: pnpm install
      - name: Install hapi
        run: yarn add @hapi/hapi@${{ matrix.hapi-version }} -D
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
